import Foundation

/// All daily reflection questions.
/// qId is 1-indexed (1…\(Questions.count)).
enum Questions {

    static let count = 210

    // MARK: - Chinese
    static let zh: [String] = [
        "你今天最想感谢的一件事是什么？",
        "用三个词描述今天的心情。",
        "你最近学到的一件新事物是什么？",
        "今天你帮助了谁，或者谁帮助了你？",
        "你现在最享受的一件小事是什么？",
        "如果明天可以做任何事，你会做什么？",
        "你对未来一年最大的期待是什么？",
        "你最近读过或听过的一句话让你印象深刻是什么？",
        "你今天有没有做一件让自己骄傲的事？",
        "你现在最想见的人是谁？",
        "你上一次大笑是因为什么？",
        "你最近最大的挑战是什么？",
        "描述一个让你感到平静的地方。",
        "你现在最想学的技能是什么？",
        "今天有什么让你感到惊喜的事？",
        "你最近做过最勇敢的一件事是什么？",
        "你对自己最满意的一个特点是什么？",
        "如果可以给一年前的自己一个建议，你会说什么？",
        "你今天花时间做了什么真正重要的事？",
        "你最近有没有放下了某件事或某段关系？感觉如何？",
        "你现在的生活里，什么是你最珍视的？",
        "你最近有没有尝试过新事物？是什么？",
        "你今天有没有对自己说一句好话？",
        "你最喜欢的一个童年记忆是什么？",
        "如果今天是你人生的最后一天，你最不舍的是什么？",
        "你认为什么样的人是真正快乐的人？",
        "你最近有什么想法一直在脑子里转？",
        "你觉得自己的哪个习惯最值得坚持？",
        "今天你有没有做一件对自己好的事？",
        "你最近一次感到充满能量是什么时候？",
        "你现在最想改变生活中的哪一件事？",
        "你最近有没有和某人产生真正的连接？",
        "你对什么事情感到最好奇？",
        "今天你有没有花时间在自然中或安静的地方？",
        "你最近一次感到骄傲是什么时候？",
        "你有没有一件一直想做但还没开始的事？",
        "你觉得现在的自己和一年前相比，最大的变化是什么？",
        "你今天的注意力主要放在了哪里？",
        "你最喜欢的一种表达爱的方式是什么？",
        "如果有人现在问你「你还好吗」，你会怎么回答？",
        "你最近有没有感到孤独？是什么让你这样感受的？",
        "你最想对某个人说但还没说出口的话是什么？",
        "你现在生活中最大的干扰是什么？",
        "你最近一次感受到被理解是什么时候？",
        "如果你能改变世界上的一件事，你会改变什么？",
        "你觉得「成功」对你意味着什么？",
        "今天你有没有做一件事只是因为它让你快乐？",
        "你最近有没有感到迷茫？是关于什么的？",
        "你最欣赏你最好朋友的哪一点？",
        "你认为爱一个人最重要的方式是什么？",
        "你最近有没有做一件对环境或他人有益的事？",
        "你现在对什么感到兴奋？",
        "你今天有没有说了什么你后来后悔的话？",
        "你最近一次感到真正放松是什么时候？",
        "如果你可以重新选择一次，你会改变哪个决定？",
        "你觉得哪一段友谊对你影响最深？",
        "你今天最想忘记的一件事是什么？",
        "你最近有没有感到愤怒？是什么引发的？",
        "你最重要的一个人生目标是什么？",
        "你现在最需要的支持是什么类型的？",
        "你认为什么让一段关系长久？",
        "你最近有什么让你感到骄傲但没有和别人分享的事？",
        "你现在处于一个你想待的地方吗？",
        "你最近一次哭是什么时候，因为什么？",
        "你最感激生命里的哪三件事？",
        "你现在内心有什么放不下的事？",
        "你最想拥有哪一种品质？",
        "今天你是否比昨天更好地照顾了自己？",
        "你对自己承诺过但还没实现的事情是什么？",
        "你最近有没有因为某件事感到嫉妒？你从中了解到自己的什么？",
        "如果你能给十年后的自己一封信，你会写什么？",
        "你现在最难接受的关于自己的事是什么？",
        "你有没有一种爱好让你完全忘记时间？",
        "今天你有没有选择了善良，即使这不容易？",
        "你最近有没有感到被误解？",
        "你最愿意为什么事情牺牲睡眠？",
        "你认为什么是真正的勇气？",
        "你现在最想去的一个地方是哪里？",
        "你今天有没有学到了关于自己的新东西？",
        "你觉得你的价值观和你的行为是否一致？",
        "你最近有没有感到被忽视？",
        "你觉得什么让你的生活有意义？",
        "你今天有没有接受了一个你通常会拒绝的邀请或机会？",
        "你最近睡眠怎么样？这反映了你的什么状态？",
        "你现在最担心的一件事是什么？",
        "你上一次真正放下手机、专注于当下是什么时候？",
        "你认为什么样的生活叫做「活得充实」？",
        "你今天有没有做了一件超出自己舒适区的事？",
        "你最近有没有感到时间不够用？为什么？",
        "如果你的生命只剩一年，你会如何度过？",
        "你现在的生活里，什么是你一直在忽视却知道很重要的？",
        "你最近对什么感到厌倦？",
        "你有没有因为害怕别人的评价而放弃过某件事？",
        "你认为什么是健康的界限感？",
        "你上一次感到真正的惊奇是什么时候？",
        "你今天是否对某人比平时多了一点耐心？",
        "你最近有没有向别人道歉或原谅了别人？",
        "你觉得现在的你是否在活出真实的自己？",
        "今天你最想做的一件还没做的事是什么？",
        "你觉得什么事情你一直在推迟，但其实今天就可以开始？",
        "你今天收到了什么让你感到温暖的话或举动？",
        "描述你理想中的一个普通的早晨。",
        "你今天有没有做了一件你以前不会做的事？",
        "你现在最希望家人了解你的哪一点？",
        "你最近有没有感到某件事让你的内心特别平静？",
        "你觉得你的身体现在在告诉你什么？",
        "你今天有没有认真听了另一个人说话？",
        "你上一次做一件「无用但快乐」的事是什么时候？",
        "你最近有没有感到自己被某段关系滋养了？",
        "你觉得你最好的一面，最常在哪些时刻出现？",
        "你今天有什么想法不敢说出口？",
        "你认为什么样的对话是真正有意义的？",
        "你最近有没有帮助过一个陌生人？",
        "你现在有没有某种执念，你觉得是时候放下了？",
        "你最近一次感到真正被爱是什么时候？",
        "你觉得你的哪种情绪是你平时最压抑的？",
        "你对自己现在的生活，打多少分？为什么？",
        "你今天有没有因为某件小事感到开心？",
        "你认为自己和五年前相比，最大的成长是什么？",
        "你有没有感到某段友谊正在疏远？你希望如何？",
        "你觉得什么是真正的自由？",
        "今天有没有什么让你感到不安全感的时刻？",
        "你最近有没有做了一件只为自己、不为任何人的事？",
        "你最感激的一个人是谁？你有没有告诉过他们？",
        "你今天有没有让某个人感到被看见？",
        "你觉得你的人生目前最大的「未竟之事」是什么？",
        "你最近有没有感到某种你说不清楚的悲伤？",
        "如果你可以和任何历史人物交谈，你会选谁，问什么？",
        "你觉得你最近是否在做一些不符合自己价值观的事？",
        "你上一次感到「一切都值得」是什么时候？",
        "你认为什么是真正的成熟？",
        "你今天有没有提醒自己慢下来？",
        "你最近有没有因为某件事感到希望？",
        "你觉得现在的你，是否在朝着你想要的方向走？",
        "你上一次感到真正的好奇是什么时候？",
        "你今天有没有做了一件让你感到「这才是我」的事？",
        "你觉得什么阻止了你变得更快乐？",
        "你最近有没有感到某段时间特别「活着」？",
        "你最想对未来的自己说什么？",
        "如果你可以选择，你希望被如何记住？",
        "你今天有没有感到某种你难以命名的情绪？",
        "你最近感受到什么样的变化正在发生？",
        "你觉得你现在最需要的是时间、金钱、还是爱？",
        "今天你有没有注意到一件平时忽略的美好事物？",
        "你认为什么是你生命中最重要的事情？",
        "你今天有没有感到自己是某个比自己更大的事物的一部分？",
        "你最近有没有对某件事感到后悔？",
        "你觉得什么让你感到「在家」？",
        "你最近一次感到迷失是什么时候，你是如何找回自己的？",
        "你今天有什么感谢自己的地方？",
        "你觉得你现在处于人生的哪个「章节」？",
        "你最近有没有遇到一个让你钦佩的人？",
        "你今天有没有允许自己休息？",
        "如果你现在可以打一个电话，你会打给谁？",
        "你最近有没有做了一件让你感到有点害怕但值得的事？",
        "你今天给自己打几分？你希望明天达到几分？",
        "你觉得什么让你在忙碌中仍然保持平衡？",
        "你最近有没有重新联系上一个久违的朋友？",
        "你今天有没有做了一件以前认为自己不会做的事？",
        "你对自己现在的某个选择，是否感到迷茫？",
        "你最近在哪件事上最专注、最投入？",
        "你觉得你今天的状态，是昨天做的哪件事影响的？",
        "你觉得什么让你感到充实而不是忙碌？",
        "你今天有没有感到某种平静，即使一切还未解决？",
        "你认为你现在处于一个值得珍惜的阶段吗？",
        "你最近有没有感到某件事比你想象中更难？",
        "你今天最值得庆祝的一件事是什么？",
        "你觉得什么是你无论如何都不愿失去的？",
        "你最近有没有做了一件事让你感到更像自己？",
        "你今天有没有在一件小事上找到了某种意义？",
        "你觉得你现在的内心是什么颜色的？",
        "你最近有没有感到某种说不清楚的满足感？",
        "你今天有没有花时间思考而不是行动？",
        "如果你的人生是一部电影，现在正处于哪一幕？",
        "你觉得你最近对自己够不够温柔？",
        "你今天有没有注意到别人的某个细节？",
        "你最近有没有感到自己在「扮演」一个角色，而不是真实地活着？",
        "你今天对自己说了什么？是鼓励还是批评？",
        "你最想把时间花在什么上面？",
        "你今天有没有被一件普通的事感动？",
        "你现在觉得什么是你生活中最大的礼物？",
        "你最近有没有感到某种恐惧在减少？",
        "你今天有没有感到自己在成长？",
        "你觉得什么让你感到有能量？",
        "你最近有没有和自己独处的时间？感觉如何？",
        "你今天最想留住的一个瞬间是什么？",
        "你认为什么是对一个人最大的尊重？",
        "你最近有没有感到某种事情正在走向终结？",
        "你今天有没有在某件事上比以前做得更好？",
        "你觉得你的日常生活是否有足够的美感和意义？",
        "你最近有没有接受了自己某个不完美的部分？",
        "你今天有没有感到时间是你的？",
        "你最想让自己相信的一件事是什么？",
        "你今天有没有感到某种事让你的心放下来了？",
        "你最近有没有发现一件让你惊喜的小事？",
        "你觉得什么使你与众不同？",
        "你今天有没有做了一件真正为他人的事？",
        "你对未来最深的一个愿望是什么？",
        "你觉得你现在的人生中什么是最真实的？",
        "今天，你在等什么？",
        "你最近有没有感到某种事让你更相信自己了？",
        "你今天最感到活着的时刻是什么？",
        "描述今天你内心最诚实的一刻。",
        "你觉得你现在最需要允许自己做的事情是什么？",
        "今天结束时，你最想记住的是什么？",
        "你相信自己可以拥有你真正想要的生活吗？为什么？",
        "如果用一个词概括你现在的状态，是什么？",
        "你今天，是否感到自己被好好对待了？",
        "你觉得什么是你这一年最深刻的领悟？",
        "写下今天你内心最想说的一句话。",
    ]

    // MARK: - English
    static let en: [String] = [
        "What is the one thing you're most grateful for today?",
        "Describe today's mood in three words.",
        "What's something new you've learned recently?",
        "Who did you help today, or who helped you?",
        "What's a small thing you're enjoying right now?",
        "If you could do anything tomorrow, what would it be?",
        "What's your biggest hope for the coming year?",
        "What's a quote or idea you've come across recently that stayed with you?",
        "Did you do something today that made you proud?",
        "Who do you most want to see right now?",
        "What was the last thing that made you laugh?",
        "What's your biggest challenge lately?",
        "Describe a place that makes you feel at peace.",
        "What skill do you most want to learn right now?",
        "What surprised you today?",
        "What's the bravest thing you've done recently?",
        "What's one quality about yourself that you're most satisfied with?",
        "If you could give your past self one piece of advice, what would it be?",
        "What truly important thing did you make time for today?",
        "Have you let go of something or someone recently? How does it feel?",
        "What do you treasure most in your life right now?",
        "Have you tried something new recently? What was it?",
        "Did you say something kind to yourself today?",
        "What's one of your favorite childhood memories?",
        "If today were your last day, what would you miss most?",
        "What does a truly happy person look like to you?",
        "What thought keeps returning to your mind lately?",
        "Which habit of yours is most worth keeping?",
        "Did you do something good for yourself today?",
        "When did you last feel full of energy?",
        "What's one thing you'd most like to change in your life right now?",
        "Have you made a genuine connection with someone recently?",
        "What are you most curious about?",
        "Did you spend any time in nature or somewhere quiet today?",
        "When did you last feel proud?",
        "Is there something you've always wanted to do but haven't started?",
        "How have you changed most compared to a year ago?",
        "Where did your attention go today?",
        "What's your favorite way to show love?",
        "If someone asked you 'Are you okay?' right now, what would you honestly say?",
        "Have you felt lonely recently? What caused it?",
        "What's something you've wanted to say to someone but haven't yet?",
        "What's the biggest distraction in your life right now?",
        "When did you last feel truly understood?",
        "If you could change one thing about the world, what would it be?",
        "What does 'success' mean to you?",
        "Did you do something today simply because it made you happy?",
        "Have you felt lost recently? About what?",
        "What do you admire most about your closest friend?",
        "What do you think is the most important way to love someone?",
        "Have you done something good for others or the planet recently?",
        "What are you excited about right now?",
        "Did you say something today that you later regretted?",
        "When did you last feel truly relaxed?",
        "If you could make one decision over again, which would it be?",
        "Which friendship has shaped you most deeply?",
        "What's one thing you'd most like to forget about today?",
        "Have you felt angry recently? What triggered it?",
        "What's your most important life goal?",
        "What kind of support do you need most right now?",
        "What do you think makes a relationship last?",
        "Is there something you've been proud of recently but haven't shared?",
        "Are you in a place you want to be right now?",
        "When was the last time you cried, and why?",
        "What are three things you're most grateful for in life?",
        "What's weighing on your heart right now?",
        "What quality do you most wish you had?",
        "Are you taking better care of yourself today than yesterday?",
        "What's something you promised yourself but haven't yet done?",
        "Have you felt jealous of something recently? What did that reveal about you?",
        "If you could write a letter to yourself ten years from now, what would you say?",
        "What's the hardest thing about yourself to accept right now?",
        "Do you have a hobby that makes you lose track of time?",
        "Did you choose kindness today, even when it wasn't easy?",
        "Have you felt misunderstood recently?",
        "What would you happily lose sleep over?",
        "What does true courage look like to you?",
        "Where do you most want to go right now?",
        "Did you learn something new about yourself today?",
        "Do you feel your values and your actions are aligned?",
        "Have you felt overlooked recently?",
        "What gives your life meaning?",
        "Did you accept an invitation or opportunity today that you'd normally pass on?",
        "How has your sleep been lately? What does that say about where you are?",
        "What are you most worried about right now?",
        "When did you last put your phone down and be fully present?",
        "What does a life 'well-lived' mean to you?",
        "Did you do something outside your comfort zone today?",
        "Have you felt rushed for time recently? Why?",
        "If you had only one year left, how would you spend it?",
        "What in your life are you consistently ignoring, even though you know it matters?",
        "What are you tired of lately?",
        "Have you ever given something up because you feared others' judgment?",
        "What do you think healthy boundaries look like?",
        "When did you last feel truly amazed?",
        "Were you a little more patient with someone today than usual?",
        "Have you apologized to someone or forgiven someone recently?",
        "Are you living as your true self right now?",
        "What's one thing you most want to do today that you haven't done yet?",
        "What have you been putting off that you could actually start today?",
        "What kind or warm thing did you receive today — a word, a gesture?",
        "Describe your ideal ordinary morning.",
        "Did you do something today that you once thought you couldn't?",
        "What do you most want your family to understand about you right now?",
        "Have you experienced a moment of deep inner peace recently?",
        "What is your body telling you right now?",
        "Did you really listen to someone today?",
        "When did you last do something 'useless but joyful'?",
        "Have you felt nourished by a relationship recently?",
        "When does your best self most often show up?",
        "What thoughts are you afraid to voice today?",
        "What makes a conversation truly meaningful to you?",
        "Have you helped a stranger recently?",
        "Is there something you've been holding onto that it's time to release?",
        "When did you last feel truly loved?",
        "Which emotion do you tend to suppress most?",
        "How would you rate your life right now, and why?",
        "Did something small make you happy today?",
        "What's the biggest way you've grown compared to five years ago?",
        "Do you feel a friendship fading? What do you hope for?",
        "What does true freedom mean to you?",
        "Was there a moment today when you felt insecure?",
        "Have you done something recently just for yourself, for no one else?",
        "Who are you most grateful for? Have you told them?",
        "Did you help someone feel seen today?",
        "What is the greatest unfinished work of your life right now?",
        "Have you felt an inexplicable sadness recently?",
        "If you could talk to any historical figure, who would it be and what would you ask?",
        "Do you feel you've been doing things that go against your values lately?",
        "When did you last feel like 'it was all worth it'?",
        "What does true maturity mean to you?",
        "Did you remind yourself to slow down today?",
        "Have you felt hopeful about something recently?",
        "Are you moving in the direction you truly want to go?",
        "When did you last feel genuinely curious?",
        "Did you do something today that felt authentically you?",
        "What do you think is holding you back from being happier?",
        "Have you had a stretch recently when you felt especially alive?",
        "What do you most want to say to your future self?",
        "If you could choose how to be remembered, how would it be?",
        "Did you experience an emotion today that you couldn't quite name?",
        "What kind of change do you sense happening in your life lately?",
        "What do you need most right now — time, money, or love?",
        "Did you notice something beautiful today that you'd normally overlook?",
        "What do you believe is the most important thing in your life?",
        "Did you feel like part of something larger than yourself today?",
        "Have you regretted something recently?",
        "What makes you feel at home?",
        "When did you last feel lost, and how did you find yourself again?",
        "What are you grateful to yourself for today?",
        "What 'chapter' of your life do you feel you're in right now?",
        "Have you encountered someone you truly admired recently?",
        "Did you allow yourself to rest today?",
        "If you could make one phone call right now, who would you call?",
        "Have you done something recently that scared you a little, but was worth it?",
        "How would you rate yourself today? What score do you hope for tomorrow?",
        "What keeps you balanced when life gets busy?",
        "Have you reconnected with a long-lost friend recently?",
        "Did you do something today that you once thought you couldn't?",
        "Are you feeling uncertain about a choice you're making right now?",
        "What have you been most focused and absorbed in lately?",
        "How did what you did yesterday shape how you feel today?",
        "What makes you feel full rather than just busy?",
        "Did you experience a sense of peace today, even amid uncertainty?",
        "Do you feel you're in a stage of life worth cherishing?",
        "Have you found something harder than expected recently?",
        "What's worth celebrating about today?",
        "What is something you would never want to lose?",
        "Have you done something recently that made you feel more like yourself?",
        "Did you find meaning in something small today?",
        "What color does your inner world feel like right now?",
        "Have you felt a quiet, hard-to-name satisfaction recently?",
        "Did you take time to think rather than just act today?",
        "If your life were a film, what scene would you be in right now?",
        "Have you been gentle enough with yourself lately?",
        "Did you notice a small detail about someone today?",
        "Have you felt like you were playing a role lately, rather than truly living?",
        "What did you say to yourself today — encouragement or criticism?",
        "What do you most want to spend your time on?",
        "Were you moved by something ordinary today?",
        "What feels like the greatest gift in your life right now?",
        "Have you felt a fear beginning to fade recently?",
        "Did you feel yourself growing today?",
        "What gives you energy?",
        "Have you had time alone with yourself recently? How did it feel?",
        "What moment from today do you most want to hold onto?",
        "What do you think is the greatest form of respect for another person?",
        "Have you sensed something in your life coming to an end recently?",
        "Did you do something better today than before?",
        "Does your daily life have enough beauty and meaning?",
        "Have you accepted an imperfect part of yourself recently?",
        "Did you feel like your time was your own today?",
        "What's the one thing you most want to believe about yourself?",
        "Did something settle in your heart today?",
        "Have you discovered a small surprise recently?",
        "What makes you different from everyone else?",
        "Did you do something today that was genuinely for someone else?",
        "What is your deepest wish for the future?",
        "What feels most real in your life right now?",
        "Today — what are you waiting for?",
        "Have you felt more confident in yourself because of something recently?",
        "What was the moment today when you felt most alive?",
        "Describe the most honest moment you had with yourself today.",
        "What do you need to give yourself permission to do?",
        "When this day ends, what do you most want to remember?",
        "Do you believe you can have the life you truly want? Why or why not?",
        "If one word could capture your state right now, what would it be?",
        "Did you feel well treated today?",
        "What is the deepest insight you've had this year?",
        "Write down the one sentence your heart most wants to say today.",
    ]

    /// Returns the question for a given qId (1-indexed) and language code.
    static func question(qId: Int, lang: String) -> String {
        let idx = max(0, min(qId - 1, count - 1))
        return lang == "zh" ? zh[idx] : en[idx]
    }

    /// Converts a qId to a human-readable date string (month/day).
    static func dateString(qId: Int, lang: String) -> String {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone.current
        var comps = DateComponents(year: 2024, day: qId)  // 2024 = leap year for safety
        comps.month = nil
        // Use ordinality approach: day qId of year
        let start = cal.date(from: DateComponents(year: 2024, month: 1, day: 1))!
        let target = cal.date(byAdding: .day, value: qId - 1, to: start)!
        let fmt = DateFormatter()
        fmt.locale = Locale(identifier: lang == "zh" ? "zh_CN" : "en_US")
        fmt.dateFormat = lang == "zh" ? "M月d日" : "MMM d"
        return fmt.string(from: target)
    }
}